[package]
name = "api_dz"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.11.27", features = ["json"]}
tokio = {version = "1.44.2", features = ["full"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
